### ISSUE TITLE
Send selection 

### ISSUE THREAD

**Issue by sglyon** [callahanrts/slack-chat#11]
I would love to see a feature where I can send selected text as a direct message or to a channel. This is my most used feature of the sublime package. 

Do you think it is doable here?

**Comment by callahanrts** [comment]
Yeah, that sounds doable. I'll add it to the todo list!

**Comment by sglyon** [comment]
Excellent. I don't know much (any) coffee script, but if there is something I can do to hurry this along let me know!

**Comment by sglyon** [comment]
So this has been implemented?!

:clap:

**Comment by callahanrts** [comment]
It's in the list :) It'll be implemented along with regular file uploads, displaying/downloading files, etc. The next 4 items in the todo will likely be done together. Probably this week/end.

**Comment by sglyon** [comment]
Excellent. Great work on the package

**Comment by callahanrts** [comment]
Selection uploads to one or more channels is supported as of 3.1.8. See [the wiki](https://github.com/callahanrts/slack-chat/wiki/Keybindings) for binding the command to a key.
