### ISSUE TITLE
Keyboard shortcuts for common operations

### ISSUE THREAD

**Issue by sglyon** [callahanrts/slack-chat#12]
I would like to be able to return from a particular conversation to the list of groups/channels/DMs  without using the mouse to click the `<` in the top corner.

Switching to a different conversation via a keybinding (a la the `cmd-k` keybinding in the OS X slack app)

It would also be nice to have a shortcut to swap focus between slack-chat and the editor, similar to how `ctrl-0` does this for the tree view (at least on OS X).

Also being able to move up/down in a chat history or list of topics using arrow keys (when slack-chat is in focus) would be great.

Essentially I want to be able to use this like I use the desktop slack app: purely by keyboard. A big ask, I know, but it would be great :smile:

**Comment by callahanrts** [comment]
Thanks for pointing this out. These are all things that were working in the old version of the slack-chat package. I fell pretty far behind atom's updates and slack introduced a real time messaging api so I've been rebuilding it. The current state of this package is really just the bare minimum to get it running again. All of the older features will be added back soon--including keybindings for pretty much everything (I absolutely hate using the mouse in my text editor :). 

When I've added the common commands, I'll document them so they can be overridden in your `keymap.cson` and post back here!

**Comment by sglyon** [comment]
Great! Thank you.

Excited to see the new real time messaging API in action.

**Comment by callahanrts** [comment]
I added some basic keybindings and documented them in [the wiki](https://github.com/callahanrts/slack-chat/wiki/Slack-Chat-Keybindings).
