### ISSUE TITLE
Change slack-chat:open-conversation Default Keybinding

### ISSUE THREAD

**Issue by caffeinewriter** [callahanrts/slack-chat#2]
While I'm assuming this keybinding works fine on Mac, on Windows/Linux, `Ctrl-o` is assigned to opening files. I suggest adding a modifier like `Cmd-ctrl-o`, or `ctrl-alt-o` on Windows/Linux.

**Comment by deadbits** [comment]
Just a suggestion but you can edit key bindings manually by changing the slack-chat.cson file for this package, or use the 'Key Binding Resolver' package to see what conflicts where then select the file you which to change.

**Comment by callahanrts** [comment]
Watch conversation at #12 for updates on default keybindings and customization.
