### ISSUE TITLE
scrolling to bottom removes top-bar

### ISSUE THREAD

**Issue by JeanMertz** [callahanrts/slack-chat#25]
not completely scrolled to bottom:

![noscroll](https://cloud.githubusercontent.com/assets/383250/8397096/35cc4878-1dc0-11e5-897c-7a089f651cf6.jpg)

scrolled to bottom:

![scroll](https://cloud.githubusercontent.com/assets/383250/8397097/39911f2e-1dc0-11e5-9760-a1117946963f.jpg)
- top-bar (with back button) scrolls out of view
- input field scrolls past bottom border

**Comment by callahanrts** [comment]
fixed
