### ISSUE TITLE
Private (joined) rooms aren't shown

### ISSUE THREAD

**Issue by JeanMertz** [callahanrts/slack-chat#26]
It looks like private rooms (which I joined, and can see in the official Slack app) aren't showing up in the side panel.

**Comment by callahanrts** [comment]
added support for private channels (groups). Weird that slack has them as separate entities.

**Comment by JeanMertz** [comment]
works perfectly. Thanks for this (and all the other issues you solved quickly :+1:)

**Comment by callahanrts** [comment]
No problem! Thanks for reporting them.
