### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by deadbits** [callahanrts/slack-chat#3]
In keymaps/slack-chat.cson: Use the `atom-workspace` tag instead of the `workspace` class.

![screen shot 2015-03-02 at 9 17 16 pm](https://cloud.githubusercontent.com/assets/1332757/6455393/8bf2208e-c121-11e4-806d-51c765cd3de6.png)

I tried creating this edit myself in the ~/.atom location for slack-chat.cson and even after a save I've still been getting the deprecated errors. Atom suggested I make a GH issue so here I am. If my fix worked, this would be a pull req :disappointed:

**Comment by asarenski** [comment]
@deadbits This pull request has been merge. Thanks!
