### ISSUE TITLE
How to configure slack-chat for atom

### ISSUE THREAD

**Issue by skjorrface** [callahanrts/slack-chat#36]
I followed the guide in description and set http://0.0.0.0:36347/oauth as redirect uri in slack app but when I restart atom and click in "Authorize" nothing happens because obviously http://0.0.0.0:36347/oauth is unreachable

**Comment by callahanrts** [comment]
Slack chat starts a server that listens for `http://0.0.0.0:36347/oauth`. I just ran through the install again myself and didn't run into any issues. After slack-chat opens the browser and you click authorize, you won't see anything other than a message telling you that you can close the window. At this point, everything should be configured properly. Try opening the command palette and executing `Slack Chat: Toggle`

If you get an error somewhere, feel free to reopen the issue with the error message.

**Comment by skjorrface** [comment]
When I configure slack and restart it a popup window of my browser opens and takes me to slack where I'm told to authorize the third party app, when I do this my browser tries to reach http://0.0.0.0:36347/oauth but I get a 404 error, the page isn't found. I'm running atom under Windows 10, maybe is this the problem?
