### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by sriharshakappala** [callahanrts/slack-chat#41]
Hi Cody,

Am just wondering if I am the only person unable to setup the slack-chat on Atom. I generated the client id and secret, pasted it in the Settings tab in Atom package. According to the instructions quoted (`When the browser opens, select the team you'd like to use with atom`) nothing is opening on my browser when I pasted them. Is there something which I am missing?

**Comment by callahanrts** [comment]
The browser should open if you quit Atom and relaunch it. Which OS are you on? I think there have been some problems with Windows in the past.

**Comment by sriharshakappala** [comment]
@callahanrts Not sure why, but I have uninstalled the package and reinstalled, and then it worked fine. I am on Ubuntu 14.04 and using Atom 1.8.x. Thank you!
